# Generated by Django 4.0.1 on 2022-04-04 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_watchlist_listingcomments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='final_bid',
            field=models.FloatField(default=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0, message='Starting bid should be 0 or greater')])),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='starting_bid',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0, message='Starting bid should be 0 or greater')]),
        ),
    ]
