# Generated by Django 4.0.1 on 2022-04-04 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_final_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='final_bid',
            field=models.FloatField(blank=True, default=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0, message='Starting bid should be 0 or greater')])),
        ),
    ]
