# Generated by Django 4.0.1 on 2022-04-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlistings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcomments',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listingbids',
            name='listing_status',
            field=models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost'), ('Active', 'Active')], default='Active', max_length=6),
        ),
    ]
